name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15
    - name: Lint
      run: |
        make install-linter
        make run-linter
    - name: Tests
      run: make run-unit-tests
    - name: Build
      run: go build -v ./...


